### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [mushtaKV/mushtaKV.github.io#4]
http://joxi.ru/52aYgPkS6pb720
сделай сайт на весь экран и чтоб не улетало все сделай контейнер

**Comment by mushtaKV** [comment]
Сделал.

**Comment by AndriiLitvin** [comment]
http://joxi.ru/brR6zPluQyozWr
1) фон менюшки должен быть на весь экран

**Comment by mushtaKV** [comment]
Пофиксил менюшку.

**Comment by AndriiLitvin** [comment]
да но ты не смотришь дальше. теперь она улетает вправо при большом экране. сделай контейнер задай ширину например 1215рх и отценрируй а внутрь запихни контент хедера

**Comment by mushtaKV** [comment]
Теперь, походу, пофиксил.

**Comment by AndriiLitvin** [comment]
Зачет
